#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
#ifdef SWAP_HANDS_ENABLE
const keypos_t PROGMEM hand_swap_config[MATRIX_ROWS][MATRIX_COLS] = {
    // Left
    {{0, 4}, {1, 4}, {2, 4}, {3, 4}, {4, 4}, {5, 4}},
    {{0, 5}, {1, 5}, {2, 5}, {3, 5}, {4, 5}, {5, 5}},
    {{0, 6}, {1, 6}, {2, 6}, {3, 6}, {4, 6}, {5, 6}},
    {{0, 7}, {1, 7}, {2, 7}, {3, 7}, {4, 7}, {5, 7}},
    // Right
    {{0, 0}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {5, 0}},
    {{0, 1}, {1, 1}, {2, 1}, {3, 1}, {4, 1}, {5, 1}},
    {{0, 2}, {1, 2}, {2, 2}, {3, 2}, {4, 2}, {5, 2}},
    {{0, 3}, {1, 3}, {2, 3}, {3, 3}, {4, 3}, {5, 3}}
};
#endif

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_TAB, KC_GRV, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, MO(3), KC_A, KC_LALT, KC_LGUI, KC_LCTL, KC_LSFT, KC_RSFT, KC_RCTL, KC_RGUI, KC_RALT, KC_COMM, KC_DOT, MO(2), MO(1), KC_SPC, KC_ENT, MO(1), MO(2)),
    [1] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_0, KC_LCBR, KC_LPRN, KC_RPRN, KC_RCBR, KC_DLR, KC_UNDS, KC_EQL, KC_TRNS, KC_NO, KC_NO, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_QUES, KC_PIPE, KC_NO, KC_Q, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_P, KC_NO, MO(4), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(4)),
    [2] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_EXLM, KC_LBRC, KC_LT, KC_GT, KC_RBRC, KC_NO, KC_MINS, KC_PLUS, KC_NO, KC_NO, KC_NO, KC_X, KC_C, KC_V, KC_V, KC_B, KC_B, KC_N, KC_M, KC_SLSH, KC_BSLS, KC_NO, KC_Z, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_TRNS, MO(4), KC_TRNS, KC_TRNS, MO(4), KC_TRNS),
    [3] = LAYOUT_split_3x6_3(KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, CG_SWAP, KC_F11, KC_BRID, KC_BRIU, KC_MUTE, KC_VOLD, KC_VOLU, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_AGIN, CG_NORM, KC_TRNS, KC_WREF, KC_WSCH, KC_MPRV, KC_MPLY, KC_MNXT, KC_CUT, KC_COPY, KC_PSTE, KC_FIND, KC_UNDO, CG_TOGG, MS_LEFT, MS_UP, MS_BTN1, MS_BTN2, MS_DOWN, MS_RGHT),
    [4] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_TRNS, KC_TRNS)
};